### ISSUE TITLE
Error Running PyCript on Macbook Air M1 | command not found

### ISSUE THREAD

**Issue by gchib297** [Anof-cyber/PyCript#8] opened 2024-05-06 12:34 UTC
**Have you gone through the Documentation or Video Tutorial**
 - Documentation - https://pycript.souravkalal.tech/
 - Video - https://youtu.be/J8KE5VR8yDk?si=yr4XqqwWh5ms7O6s
 - [Y/N] - Y

**Describe the bug**
_Documenting it here for reference if someone faces same issue in future. Thank you for the awesome work!_

PyCript could not correctly determine path of installed python and node and logged following error on Log tab:
`/bin/sh: python: command not found`

Workaround for me was to use absolute paths in file ./pycript/execution.py at L8 and L10 as suggested in python doc [here](https://docs.python.org/3/library/subprocess.html#subprocess.Popen:~:text=Warning%20For%20maximum%20reliability%2C%20use%20a%20fully%20qualified%20path%20for%20the%20executable.)

```
        if selectedlang == "JavaScript":
            command.extend(["/usr/local/bin/node", '"' + path + '"'])  # Surround path with double quotes
        elif selectedlang == "Python":
            command.extend(["/usr/local/bin/python3", '"' + path + '"'])  # Surround path with double quotes
``` 
@Anof-cyber maybe determining path at runtime using shutil.which() would help here?

**To Reproduce**
1. Install PyCript from BAppStore or github
2. Configure the required options in Config tab
3. Enable logging in Log tab
4. Try to encrypt or decrypt values
5. Error as stated above is displayed

**Expected behavior**
Pycript should be able to determine installation path of python and node correctly

**Screenshots**
![image](https://github.com/Anof-cyber/PyCript/assets/11896766/e22ae4b4-a0b8-4486-ace1-b41170457927)

**Desktop (please complete the following information):**
 - OS: MacOS 14.1.2 (Macbook Air M1)
 - BurpSuite Version: v2024.3.1.4
 - PyCript Version: 0.3

**Comment by impozzible** [comment] 2024-06-08 09:50
Hi @gchib297 why did you close this? having the same issue

**Comment by Anof-cyber** [comment] 2024-06-08 17:46
@impozzible The issue is not related to PyCript. The documentation mentioned that binaries/language should be accessible from anywhere in the system. The system env should have the path of the langauge binaries to allow using from anywhere in the system terminal. 

Make sure the Java/Python/node is in system environment variables and should be accessible from anywhere in terminal.

https://pycript.souravkalal.tech/latest/Prerequisites/

**Comment by YSaxon** [comment] 2024-06-28 19:25
I did a bit of debugging, and in macOS, the `python` and `node` commands running in `execution.py` end up for whatever reason being run with a barebones env in which `PATH=/usr/bin:/bin:/usr/sbin:/sbin`. All of those folders are covered by macOS's SIP which means they are not modifiable. So there is no easy way for an end user to remedy this, other than to either hardcode the paths to the binaries (which is obviously not a portable solution) or to find a way of inheriting a normal environment. I've just submitted a pull request to that effect, which calls `env` under a login shell once at init, and then passes that env to subsequent Popen calls.

**Comment by YSaxon** [comment] 2024-07-01 16:06
For anyone else who has this problem, you can try my patch here https://github.com/YSaxon/PyCript/tree/PATCH

**Comment by Anof-cyber** [comment] 2024-07-01 21:16
@YSaxon the issue has been fixed with different methods. The new commit https://github.com/Anof-cyber/PyCript/commit/46b8b8ccce79829b14d720b885fcbdba24f7825e allows you to select the executable like python.exe node etc instead of taking langauge binary from system environment.

The additional features which allow you to remove the limit of using just 3 langauge like Python Java and NodeJS. You can keep empty langauge path and use to run encrpytion decryption script as executable, which allows you to write encrpytion decryption script in compiled language like C C++ Rust  or Go etc.

**Closed as completed** 2024-07-06 17:17 UTC
Labels: enhancement
